name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile and build lambdas
        run: npm ci
        working-directory: ./lambdas/express-backend

      - name: Deploy attendance-cdk
        - name: Deploy attendance-cdk
          run: |
            npm ci
            cdk deploy --require-approval never
          working-directory: ./attendance-cdk
