name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile and build lambdas
        run: npm ci
        working-directory: ./lambdas/express-backend

      - name: Deploy attendance-cdk
        run: |
          npm ci
          output=$(cdk deploy --require-approval never)
          echo "$output" > deployment_output.txt
          echo "$output"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        working-directory: ./attendance-cdk

      - name: Add CDK Output to GitHub Actions Summary
        run: |
          echo "## AWS CDK Deployment Output" >> $GITHUB_STEP_SUMMARY
          cat ./attendance-cdk/deployment_output.txt >> $GITHUB_STEP_SUMMARY
