name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Compile and build lambdas
        run: npm ci
        working-directory: lambdas

      - name: Deploy attrandacne-cdk
        run: ccdk deploy --require-approval never
        working-directory: attrandacne-cdk